# Generated by Django 5.0.6 on 2024-06-01 21:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
                ('zip', models.IntegerField(default=0)),
                ('district', models.CharField(default='', max_length=6)),
                ('topographical_nr', models.CharField(blank=True, max_length=20)),
                ('floor', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('size', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=1)),
                ('halfrooms', models.IntegerField(default=0)),
                ('balcony_size', models.FloatField(default=0.0)),
                ('furnished', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('deposit', models.PositiveIntegerField(default=0)),
                ('overhead', models.PositiveIntegerField(default=0)),
                ('premiumPercentage', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('premium', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(15000), django.core.validators.MaxValueValidator(50000)])),
                ('next_check', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('check_status', models.BooleanField(default=True)),
                ('last_check', models.DateField(blank=True, null=True)),
                ('sent_contract', models.FileField(blank=True, null=True, upload_to='')),
                ('signed_contract', models.FileField(blank=True, null=True, upload_to='Documents')),
                ('leave_statement', models.FileField(blank=True, null=True, upload_to='Documents/')),
                ('takeover_checklist', models.FileField(blank=True, null=True, upload_to='Documents/')),
                ('child_acceptance_statement', models.FileField(blank=True, null=True, upload_to='Documents/')),
            ],
        ),
        migrations.CreateModel(
            name='DictHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_serial', models.CharField(max_length=30)),
                ('dict_date', models.DateField(auto_now_add=True)),
                ('dict_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('birth_name', models.CharField(max_length=50)),
                ('persID', models.CharField(max_length=20)),
                ('taxID', models.CharField(max_length=15)),
                ('iban', models.CharField(max_length=40)),
                ('is_company', models.BooleanField(default=False)),
                ('active_owner', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkDate', models.DateField(auto_now_add=True)),
                ('cleaning', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('damage', models.BooleanField(default=False)),
                ('animal', models.BooleanField(default=False)),
                ('equipment_damage', models.BooleanField(default=False)),
                ('not_allowed_tenants', models.BooleanField(default=False)),
                ('description', models.TextField(default=False, max_length=500)),
                ('apt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Checkhistory_Apartment', to='columbus.apartment')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ManyToManyField(related_name='apartment_owner', to='columbus.owner'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('title', models.TextField(max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Expired', 'Expired')], default='Pending', max_length=12)),
                ('task_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_responsible_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('birth_name', models.CharField(max_length=50)),
                ('persID', models.CharField(max_length=20)),
                ('taxID', models.CharField(max_length=15)),
                ('iban', models.CharField(max_length=40)),
                ('is_company', models.BooleanField(default=False)),
                ('active_tenant', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant',
            field=models.ManyToManyField(related_name='apartment_tenant', to='columbus.tenant'),
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30)),
                ('current', models.FloatField()),
                ('dict_start_day', models.PositiveIntegerField(default=1)),
                ('dict_end_day', models.PositiveIntegerField(default=7)),
                ('provider', models.CharField(default='', max_length=20)),
                ('utility_type', models.CharField(default='', max_length=10)),
                ('utility_unit', models.CharField(default='', max_length=5)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='columbus.apartment')),
                ('util_responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='util_responsible_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
